// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYbnhn5YupYGqgzJFm5r54_qP-kiAJxAk',
    appId: '1:965374299505:web:e398247e589718e327bad0',
    messagingSenderId: '965374299505',
    projectId: 'app-dictionary-d528c',
    authDomain: 'app-dictionary-d528c.firebaseapp.com',
    storageBucket: 'app-dictionary-d528c.appspot.com',
    measurementId: 'G-5ZR30YYXCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGwVlrFBaE7knH9BztYaq757q2tI6kGoU',
    appId: '1:965374299505:android:b4e904873bdd19b627bad0',
    messagingSenderId: '965374299505',
    projectId: 'app-dictionary-d528c',
    storageBucket: 'app-dictionary-d528c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQzG6X65qVWu5y9JwZDUqGGKhrIQnTQs4',
    appId: '1:965374299505:ios:165689c76af7ac8a27bad0',
    messagingSenderId: '965374299505',
    projectId: 'app-dictionary-d528c',
    storageBucket: 'app-dictionary-d528c.appspot.com',
    iosClientId: '965374299505-k79i7tmcbap3ppvb3fomkiogst1tm5bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDictionary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQzG6X65qVWu5y9JwZDUqGGKhrIQnTQs4',
    appId: '1:965374299505:ios:165689c76af7ac8a27bad0',
    messagingSenderId: '965374299505',
    projectId: 'app-dictionary-d528c',
    storageBucket: 'app-dictionary-d528c.appspot.com',
    iosClientId: '965374299505-k79i7tmcbap3ppvb3fomkiogst1tm5bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDictionary',
  );
}
